apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-k-1
  namespace: nico-demo-vm
spec:
  config: |
    {
            "cniVersion": "0.3.1", 
            "name": "ovn-k-1", 
            "type": "ovn-k8s-cni-overlay", 
            "topology":"layer2", 
            "mtu": 1300, 
            "subnets": "10.100.200.0/24",
            "netAttachDefName": "nico-demo-vm/ovn-k-1" 
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-k-1
  namespace: default
spec:
  config: |
    {
            "cniVersion": "0.3.1", 
            "name": "ovn-k-1", 
            "type": "ovn-k8s-cni-overlay", 
            "topology":"layer2", 
            "mtu": 1300, 
            "subnets": "10.100.200.0/24",
            "netAttachDefName": "default/ovn-k-1" 
    }
